# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
#
development:
   PG_HOST: '127.0.0.1'
   DBNAME: 'rocket_elevators_postgres'
   PG_USER: 'officeimac'
   PASSWORD: ''
   SLACK_API_TOKEN: 'xoxb-461156293569-2246009152352-MbdF2jUu5fe3N7MzhA8ZEqcA'
   TWILIO_ACCOUNT_SID: 'ACbab73174d6b166e5471abe651897f807'
   TWILIO_AUTH_TOKEN: 'd4ff37b02c434be43552e9db062d4841'
   GOOGLE_MAPS_API: AIzaSyBvL3upjtbPC-i4dD7Y-ORbh-CgkXgl8QE
# production:
#   pg_host: 'codeboxx-postgresql.cq6zrczewpu2.us-east-1.rds.amazonaws.com'
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
