# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
#
development:
   PG_HOST: '127.0.0.1'
   DBNAME: 'rocket_elevators_postgres'
   PG_USER: 'officeimac'
   PASSWORD: ''
   SLACK_TOKEN: https://hooks.slack.com/services/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
   DROPBOX_TOKEN: XaNMonD3fRoAAAAAAAAAASpDuc-aQyweenOg9IKT9QoXahg63wck3y_Qw1tMEhdi
   CLIENT_ID: m31whzp2umoubn7
   CLIENT_SECRET: n5eb5tjapcb0dlt
   SLACK_API_TOKEN: 'xoxb-461156293569-2246009152352-MbdF2jUu5fe3N7MzhA8ZEqcA'
   TWILIO_ACCOUNT_SID: ACbab73174d6b166e5471abe651897f807
   TWILIO_AUTH_TOKEN: d4ff37b02c434be43552e9db062d4841
   TWILIO_PHONE_1: +12048906332
   TWILIO_PHONE_2: +14182345968
   TWILIO_PHONE_3: +12048906332
   GOOGLE_MAPS_API: AIzaSyBvL3upjtbPC-i4dD7Y-ORbh-CgkXgl8QE
# production:
#   pg_host: 'codeboxx-postgresql.cq6zrczewpu2.us-east-1.rds.amazonaws.com'
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

WATSON APIKEY: 'R7FVOui8nSAdVMoHT-xOdWIVd_V-dFZYudK30uN4n0eg'
ZENDESK APIKEY: CnWgyhxn0fc85Be63CqBa0c2GJHePpjrQnuUFBO1
ZENDESK USERNAME: mathieu.dion98@gmail.com
ZENDESK PASSWORD: password1234
ZENDESK OAUTH: 254d650a567aa1b655992bbb27ec9f6c5c1c4f5e9cac6e4d655c3b083310e9bc
