# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
#
development:
   PG_HOST: '127.0.0.1'
   DBNAME: 'rocket_elevators_postgres'
   PG_USER: 'officeimac'
   PASSWORD: ''
   SLACK_TOKEN: https://hooks.slack.com/services/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
   DROPBOX_OAUTH_BEARER: sl.Az3memU5mtPU-5x505GQO-Ob74QHKqe0UqsIygUEfk7cUvobgcwcl3nnxaNzVGjlXutzSpS4rHB1RD4NOxMEV1qcXpsbs86osJlrD6bE8vjFPtlYhv2rd851CQw4K-Y02rflPLQ
   CLIENT_ID: m31whzp2umoubn7
   CLIENT_SECRET: n5eb5tjapcb0dlt


# production:
#   pg_host: 'codeboxx-postgresql.cq6zrczewpu2.us-east-1.rds.amazonaws.com'
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

# _yuxN0a0BBAAAAAAAAABVVJ7Itz8qha5K2cEVjcJOEk
